<?php

return [
    // Central module registry — each module describes itself here.
    'modules' => [
        [
            'name' => 'News',
            'slug' => 'news',
            'icon' => 'heroicon-o-document-text',
            'route' => 'admin.news.index',
            'permission_prefix' => 'News',
            'group' => 'Content',
            'order' => 10,
            'status' => 'enabled',
            'enabled' => true,
        ],
        [
            'name' => 'Gallery',
            'slug' => 'gallery',
            'icon' => 'heroicon-o-photo',
            'route' => 'admin.galleries.index',
            'permission_prefix' => 'Gallery',
            'group' => 'Content',
            'order' => 20,
            'status' => 'enabled',
            'enabled' => true,
        ],
        [
            'name' => 'Programs',
            'slug' => 'programs',
            'icon' => 'heroicon-o-briefcase',
            'route' => 'admin.programs.index',
            'policy' => 'App\\Policies\\ProgramPolicy',
            'service' => 'App\\Services\\ProgramService',
            'model' => 'App\\Models\\Program',
            'group' => 'Content',
            'navigation_group' => 'Content',
            'order' => 30,
            'version' => '1.0',
            'feature_flag' => 'programs.enabled',
            'cacheable' => true,
            'widget_enabled' => true,
            'searchable' => true,
            'permission_prefix' => 'Program',
            'sidebar_visible' => true,
            'dashboard_enabled' => true,
            'status' => 'enabled',
            'enabled' => true,
        ],
        [
            'name' => 'Services',
            'slug' => 'services',
            'icon' => 'heroicon-o-clipboard-document-list',
            'route' => 'admin.services.index',
            'policy' => 'App\\Policies\\ServicePolicy',
            'service' => 'App\\Services\\ServiceService',
            'model' => 'App\\Models\\Service',
            'group' => 'Content',
            'navigation_group' => 'Content',
            'order' => 40,
            'version' => '1.0',
            'feature_flag' => 'services.enabled',
            'cacheable' => true,
            'widget_enabled' => true,
            'searchable' => true,
            'permission_prefix' => 'Service',
            'sidebar_visible' => true,
            'dashboard_enabled' => true,
            'status' => 'enabled',
            'enabled' => true,
        ],
        [
            'name' => 'Publications',
            'slug' => 'publications',
            'icon' => 'heroicon-o-document-text',
            'route' => 'admin.publications.index',
            'policy' => 'App\\Policies\\PublicationPolicy',
            'service' => 'App\\Services\\PublicationService',
            'model' => 'App\\Models\\Publication',
            'group' => 'Content',
            'navigation_group' => 'Content',
            'order' => 50,
            'version' => '1.0',
            'feature_flag' => 'publications.enabled',
            'cacheable' => true,
            'widget_enabled' => true,
            'searchable' => true,
            'permission_prefix' => 'Publication',
            'sidebar_visible' => true,
            'dashboard_enabled' => true,
            'status' => 'enabled',
            'enabled' => true,
        ],
    ],
];
